//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jint.Native
{
    partial class JintRuntime
    {
        public static bool Operation_Equal(object left, object right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(object left, bool right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(object left, double right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(object left, string right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(bool left, object right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(bool left, double right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(bool left, string right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(double left, object right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(double left, bool right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(double left, string right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(string left, object right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(string left, bool right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(string left, double right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(object left, object right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(object left, bool right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(object left, double right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(object left, string right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(bool left, object right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(bool left, double right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(bool left, string right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(double left, object right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(double left, bool right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(double left, string right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(string left, object right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(string left, bool right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(string left, double right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_LessThan(object left, object right)
        {
            double result;
            if (TryCompareRange(left, right, out result))
                return result < 0;
            return false;
        }

        public static bool Operation_LessThan(object left, bool right)
        {
            return JsValue.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(object left, double right)
        {
            return JsValue.ToNumber(left) < right;
        }

        public static bool Operation_LessThan(object left, string right)
        {
            return JsValue.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(bool left, object right)
        {
            return JsConvert.ToNumber(left) < JsValue.ToNumber(right);
        }

        public static bool Operation_LessThan(bool left, bool right)
        {
            return JsConvert.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(bool left, double right)
        {
            return JsConvert.ToNumber(left) < right;
        }

        public static bool Operation_LessThan(bool left, string right)
        {
            return JsConvert.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(double left, object right)
        {
            return left < JsValue.ToNumber(right);
        }

        public static bool Operation_LessThan(double left, bool right)
        {
            return left < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(double left, string right)
        {
            return left < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(string left, object right)
        {
            return JsConvert.ToNumber(left) < JsValue.ToNumber(right);
        }

        public static bool Operation_LessThan(string left, bool right)
        {
            return JsConvert.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(string left, double right)
        {
            return JsConvert.ToNumber(left) < right;
        }

        public static bool Operation_LessThan(string left, string right)
        {
            return JsConvert.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(object left, object right)
        {
            double result;
            if (TryCompareRange(left, right, out result))
                return result <= 0;
            return false;
        }

        public static bool Operation_LessThanOrEqual(object left, bool right)
        {
            return JsValue.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(object left, double right)
        {
            return JsValue.ToNumber(left) <= right;
        }

        public static bool Operation_LessThanOrEqual(object left, string right)
        {
            return JsValue.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(bool left, object right)
        {
            return JsConvert.ToNumber(left) <= JsValue.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(bool left, bool right)
        {
            return JsConvert.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(bool left, double right)
        {
            return JsConvert.ToNumber(left) <= right;
        }

        public static bool Operation_LessThanOrEqual(bool left, string right)
        {
            return JsConvert.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(double left, object right)
        {
            return left <= JsValue.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(double left, bool right)
        {
            return left <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(double left, string right)
        {
            return left <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(string left, object right)
        {
            return JsConvert.ToNumber(left) <= JsValue.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(string left, bool right)
        {
            return JsConvert.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(string left, double right)
        {
            return JsConvert.ToNumber(left) <= right;
        }

        public static bool Operation_LessThanOrEqual(string left, string right)
        {
            return JsConvert.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(object left, object right)
        {
            double result;
            if (TryCompareRange(left, right, out result))
                return result > 0;
            return false;
        }

        public static bool Operation_GreaterThan(object left, bool right)
        {
            return JsValue.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(object left, double right)
        {
            return JsValue.ToNumber(left) > right;
        }

        public static bool Operation_GreaterThan(object left, string right)
        {
            return JsValue.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(bool left, object right)
        {
            return JsConvert.ToNumber(left) > JsValue.ToNumber(right);
        }

        public static bool Operation_GreaterThan(bool left, bool right)
        {
            return JsConvert.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(bool left, double right)
        {
            return JsConvert.ToNumber(left) > right;
        }

        public static bool Operation_GreaterThan(bool left, string right)
        {
            return JsConvert.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(double left, object right)
        {
            return left > JsValue.ToNumber(right);
        }

        public static bool Operation_GreaterThan(double left, bool right)
        {
            return left > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(double left, string right)
        {
            return left > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(string left, object right)
        {
            return JsConvert.ToNumber(left) > JsValue.ToNumber(right);
        }

        public static bool Operation_GreaterThan(string left, bool right)
        {
            return JsConvert.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(string left, double right)
        {
            return JsConvert.ToNumber(left) > right;
        }

        public static bool Operation_GreaterThan(string left, string right)
        {
            return JsConvert.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(object left, object right)
        {
            double result;
            if (TryCompareRange(left, right, out result))
                return result >= 0;
            return false;
        }

        public static bool Operation_GreaterThanOrEqual(object left, bool right)
        {
            return JsValue.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(object left, double right)
        {
            return JsValue.ToNumber(left) >= right;
        }

        public static bool Operation_GreaterThanOrEqual(object left, string right)
        {
            return JsValue.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(bool left, object right)
        {
            return JsConvert.ToNumber(left) >= JsValue.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(bool left, bool right)
        {
            return JsConvert.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(bool left, double right)
        {
            return JsConvert.ToNumber(left) >= right;
        }

        public static bool Operation_GreaterThanOrEqual(bool left, string right)
        {
            return JsConvert.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(double left, object right)
        {
            return left >= JsValue.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(double left, bool right)
        {
            return left >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(double left, string right)
        {
            return left >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(string left, object right)
        {
            return JsConvert.ToNumber(left) >= JsValue.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(string left, bool right)
        {
            return JsConvert.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(string left, double right)
        {
            return JsConvert.ToNumber(left) >= right;
        }

        public static bool Operation_GreaterThanOrEqual(string left, string right)
        {
            return JsConvert.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_Same(object left, object right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(object left, bool right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(object left, double right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(object left, string right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(bool left, object right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(bool left, double right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(bool left, string right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(double left, object right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(double left, bool right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(double left, string right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(string left, object right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(string left, bool right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(string left, double right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_NotSame(object left, object right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(object left, bool right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(object left, double right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(object left, string right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(bool left, object right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(bool left, double right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(bool left, string right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(double left, object right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(double left, bool right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(double left, string right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(string left, object right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(string left, bool right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(string left, double right)
        {
            return !CompareSame(left, right);
        }

    }
}
