//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jint.Native
{
    partial class JintRuntime
    {
        public static bool Operation_Equal(JsBox left, JsBox right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(JsBox left, bool right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(JsBox left, double right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(JsBox left, string right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(bool left, JsBox right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(bool left, double right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(bool left, string right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(double left, JsBox right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(double left, bool right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(double left, string right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(string left, JsBox right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(string left, bool right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_Equal(string left, double right)
        {
            return CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(JsBox left, JsBox right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(JsBox left, bool right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(JsBox left, double right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(JsBox left, string right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(bool left, JsBox right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(bool left, double right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(bool left, string right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(double left, JsBox right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(double left, bool right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(double left, string right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(string left, JsBox right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(string left, bool right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_NotEqual(string left, double right)
        {
            return !CompareEquality(left, right);
        }

        public static bool Operation_LessThan(JsBox left, JsBox right)
        {
            double result;
            if (TryCompareRange(left, right, out result))
                return result < 0;
            return false;
        }

        public static bool Operation_LessThan(JsBox left, bool right)
        {
            return left.ToNumber() < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(JsBox left, double right)
        {
            return left.ToNumber() < right;
        }

        public static bool Operation_LessThan(JsBox left, string right)
        {
            return left.ToNumber() < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(bool left, JsBox right)
        {
            return JsConvert.ToNumber(left) < right.ToNumber();
        }

        public static bool Operation_LessThan(bool left, bool right)
        {
            return JsConvert.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(bool left, double right)
        {
            return JsConvert.ToNumber(left) < right;
        }

        public static bool Operation_LessThan(bool left, string right)
        {
            return JsConvert.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(double left, JsBox right)
        {
            return left < right.ToNumber();
        }

        public static bool Operation_LessThan(double left, bool right)
        {
            return left < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(double left, string right)
        {
            return left < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(string left, JsBox right)
        {
            return JsConvert.ToNumber(left) < right.ToNumber();
        }

        public static bool Operation_LessThan(string left, bool right)
        {
            return JsConvert.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThan(string left, double right)
        {
            return JsConvert.ToNumber(left) < right;
        }

        public static bool Operation_LessThan(string left, string right)
        {
            return JsConvert.ToNumber(left) < JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(JsBox left, JsBox right)
        {
            double result;
            if (TryCompareRange(left, right, out result))
                return result <= 0;
            return false;
        }

        public static bool Operation_LessThanOrEqual(JsBox left, bool right)
        {
            return left.ToNumber() <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(JsBox left, double right)
        {
            return left.ToNumber() <= right;
        }

        public static bool Operation_LessThanOrEqual(JsBox left, string right)
        {
            return left.ToNumber() <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(bool left, JsBox right)
        {
            return JsConvert.ToNumber(left) <= right.ToNumber();
        }

        public static bool Operation_LessThanOrEqual(bool left, bool right)
        {
            return JsConvert.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(bool left, double right)
        {
            return JsConvert.ToNumber(left) <= right;
        }

        public static bool Operation_LessThanOrEqual(bool left, string right)
        {
            return JsConvert.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(double left, JsBox right)
        {
            return left <= right.ToNumber();
        }

        public static bool Operation_LessThanOrEqual(double left, bool right)
        {
            return left <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(double left, string right)
        {
            return left <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(string left, JsBox right)
        {
            return JsConvert.ToNumber(left) <= right.ToNumber();
        }

        public static bool Operation_LessThanOrEqual(string left, bool right)
        {
            return JsConvert.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_LessThanOrEqual(string left, double right)
        {
            return JsConvert.ToNumber(left) <= right;
        }

        public static bool Operation_LessThanOrEqual(string left, string right)
        {
            return JsConvert.ToNumber(left) <= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(JsBox left, JsBox right)
        {
            double result;
            if (TryCompareRange(left, right, out result))
                return result > 0;
            return false;
        }

        public static bool Operation_GreaterThan(JsBox left, bool right)
        {
            return left.ToNumber() > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(JsBox left, double right)
        {
            return left.ToNumber() > right;
        }

        public static bool Operation_GreaterThan(JsBox left, string right)
        {
            return left.ToNumber() > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(bool left, JsBox right)
        {
            return JsConvert.ToNumber(left) > right.ToNumber();
        }

        public static bool Operation_GreaterThan(bool left, bool right)
        {
            return JsConvert.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(bool left, double right)
        {
            return JsConvert.ToNumber(left) > right;
        }

        public static bool Operation_GreaterThan(bool left, string right)
        {
            return JsConvert.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(double left, JsBox right)
        {
            return left > right.ToNumber();
        }

        public static bool Operation_GreaterThan(double left, bool right)
        {
            return left > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(double left, string right)
        {
            return left > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(string left, JsBox right)
        {
            return JsConvert.ToNumber(left) > right.ToNumber();
        }

        public static bool Operation_GreaterThan(string left, bool right)
        {
            return JsConvert.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThan(string left, double right)
        {
            return JsConvert.ToNumber(left) > right;
        }

        public static bool Operation_GreaterThan(string left, string right)
        {
            return JsConvert.ToNumber(left) > JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(JsBox left, JsBox right)
        {
            double result;
            if (TryCompareRange(left, right, out result))
                return result >= 0;
            return false;
        }

        public static bool Operation_GreaterThanOrEqual(JsBox left, bool right)
        {
            return left.ToNumber() >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(JsBox left, double right)
        {
            return left.ToNumber() >= right;
        }

        public static bool Operation_GreaterThanOrEqual(JsBox left, string right)
        {
            return left.ToNumber() >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(bool left, JsBox right)
        {
            return JsConvert.ToNumber(left) >= right.ToNumber();
        }

        public static bool Operation_GreaterThanOrEqual(bool left, bool right)
        {
            return JsConvert.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(bool left, double right)
        {
            return JsConvert.ToNumber(left) >= right;
        }

        public static bool Operation_GreaterThanOrEqual(bool left, string right)
        {
            return JsConvert.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(double left, JsBox right)
        {
            return left >= right.ToNumber();
        }

        public static bool Operation_GreaterThanOrEqual(double left, bool right)
        {
            return left >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(double left, string right)
        {
            return left >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(string left, JsBox right)
        {
            return JsConvert.ToNumber(left) >= right.ToNumber();
        }

        public static bool Operation_GreaterThanOrEqual(string left, bool right)
        {
            return JsConvert.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_GreaterThanOrEqual(string left, double right)
        {
            return JsConvert.ToNumber(left) >= right;
        }

        public static bool Operation_GreaterThanOrEqual(string left, string right)
        {
            return JsConvert.ToNumber(left) >= JsConvert.ToNumber(right);
        }

        public static bool Operation_Same(JsBox left, JsBox right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(JsBox left, bool right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(JsBox left, double right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(JsBox left, string right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(bool left, JsBox right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(bool left, double right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(bool left, string right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(double left, JsBox right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(double left, bool right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(double left, string right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(string left, JsBox right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(string left, bool right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_Same(string left, double right)
        {
            return CompareSame(left, right);
        }

        public static bool Operation_NotSame(JsBox left, JsBox right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(JsBox left, bool right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(JsBox left, double right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(JsBox left, string right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(bool left, JsBox right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(bool left, double right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(bool left, string right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(double left, JsBox right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(double left, bool right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(double left, string right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(string left, JsBox right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(string left, bool right)
        {
            return !CompareSame(left, right);
        }

        public static bool Operation_NotSame(string left, double right)
        {
            return !CompareSame(left, right);
        }

    }
}
